#!/bin/bash
#
# Run E2E tests against LXC backend
#
# This script:
# 1. Ensures the soupfinance-backend LXC container is running
# 2. Gets the container IP address
# 3. Updates .env.lxc with the correct API URL
# 4. Runs Playwright E2E tests
#
# Usage:
#   ./scripts/run-e2e-with-lxc.sh           # Run all E2E tests
#   ./scripts/run-e2e-with-lxc.sh --headed  # Run with browser visible
#   ./scripts/run-e2e-with-lxc.sh auth      # Run specific test file
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOUPFINANCE_WEB_DIR="$(dirname "$SCRIPT_DIR")"
SOUPFINANCE_LXC_DIR="$(dirname "$SOUPFINANCE_WEB_DIR")/soupfinance-lxc"

echo -e "${BLUE}=== SoupFinance E2E Tests with LXC Backend ===${NC}"

# Check if setup-backend.sh exists
if [[ ! -f "$SOUPFINANCE_LXC_DIR/setup-backend.sh" ]]; then
    echo -e "${RED}Error: $SOUPFINANCE_LXC_DIR/setup-backend.sh not found${NC}"
    echo "Please run from the soupfinance-web directory"
    exit 1
fi

# Step 1: Ensure backend is running
echo -e "\n${YELLOW}[1/4] Ensuring LXC backend is running...${NC}"
if ! "$SOUPFINANCE_LXC_DIR/setup-backend.sh" --ensure-running; then
    echo -e "${RED}Failed to start LXC backend${NC}"
    exit 1
fi

# Step 2: Get backend URL
echo -e "\n${YELLOW}[2/4] Getting backend URL...${NC}"
BACKEND_URL=$("$SOUPFINANCE_LXC_DIR/get-backend-url.sh")
if [[ -z "$BACKEND_URL" ]]; then
    echo -e "${RED}Failed to get backend URL${NC}"
    exit 1
fi
echo -e "${GREEN}Backend URL: $BACKEND_URL${NC}"

# Step 3: Update .env.lxc
echo -e "\n${YELLOW}[3/4] Updating .env.lxc...${NC}"
cat > "$SOUPFINANCE_WEB_DIR/.env.lxc" << EOF
# LXC Backend Environment Configuration
# Auto-generated by run-e2e-with-lxc.sh on $(date)
#
# Backend container: soupfinance-backend
# API URL: $BACKEND_URL

VITE_API_URL=$BACKEND_URL
EOF
echo -e "${GREEN}Updated .env.lxc with VITE_API_URL=$BACKEND_URL${NC}"

# Step 4: Run E2E tests
echo -e "\n${YELLOW}[4/4] Running E2E tests...${NC}"
cd "$SOUPFINANCE_WEB_DIR"

# Parse arguments
PLAYWRIGHT_ARGS=""
HEADED=""

for arg in "$@"; do
    case $arg in
        --headed)
            HEADED="--headed"
            ;;
        --ui)
            HEADED="--ui"
            ;;
        *)
            PLAYWRIGHT_ARGS="$PLAYWRIGHT_ARGS $arg"
            ;;
    esac
done

# Run playwright with LXC config
echo -e "${BLUE}Running: npx playwright test --config=playwright.lxc.config.ts $HEADED $PLAYWRIGHT_ARGS${NC}"
npx playwright test --config=playwright.lxc.config.ts $HEADED $PLAYWRIGHT_ARGS

# Report results
if [[ $? -eq 0 ]]; then
    echo -e "\n${GREEN}=== E2E Tests Passed ===${NC}"
else
    echo -e "\n${RED}=== E2E Tests Failed ===${NC}"
    echo -e "${YELLOW}View report: npm run test:e2e:lxc:report${NC}"
    exit 1
fi
